#!/usr/bin/env bash

# Check if correct number of parameters provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Check if file exists
if [ ! -f "$FILE" ]; then
    echo "File $FILE does not exist"
    exit 1
fi

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP":~/

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File transfer successful"
else
    echo "File transfer failed"
fi
