#!/usr/bin/env bash
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo pkill apache2
sudo systemctl restart nginx

